# Generated by Django 6.0.3 on 2026-03-29 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_customer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
